name: NeoxsuchtSystemV1
version: ${project.version}
main: at.aimrose.molunar.Main
authors: [ AimRose ]

commands:
  Feed:
    description: Hunger stillen.
  Fly:
    description: Fly aktivieren/deaktiveren.
  Heal:
    description: Healen.
  Kick:
    description: Kicke eine Person.
  CC:
    description: ChatClear
  ChatClear:
    description: ChatClear
  GM:
    description: Gamemode
  Gamemode:
    description: Gamemode
  Wartung:
    description: Wartung
  Perks:
    description: Perks
  Globalmute:
    description: Chat an/aus
  Broadcast:
    description: Broadcast
  Bc:
    description: Broadcast
  Menu:
    description: Menu
  Discord:
    description: Discord
  Dc:
    description: Discord
  Teamspeak:
    description: Teamspeak
  Ts:
    description: Teamspeak
  Website:
    description: Website
  Twitter:
    description: Twitter
  Instagram:
    description: Instagram
  Insta:
    description: Instagram
  Bestrafungen:
    description: Bestrafungen
